// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL (Supabase direct, port 5432) for migrations — pooler doesn't support DDL
    // Runtime PrismaClient uses DATABASE_URL (pooled) configured in shared/lib/prisma.ts
    url: process.env["DIRECT_URL"],
  },
});
