export interface DummyProposal {
  jobTitle: string;
  jobDescription: string;
  generatedContent: string;
  jobUrl?: string;
  tone: "PROFESSIONAL" | "CONVERSATIONAL" | "CONFIDENT" | "FRIENDLY";
  formula: "AIDA" | "PAS" | "BAB" | "STAR" | "DIRECT";
  proposalLength: "SHORT" | "MEDIUM" | "LONG";
  upworkOpener: boolean;
  status: "REPLIED" | "WON" | "NO_RESPONSE" | null;
}

export const DUMMY_PROPOSALS: DummyProposal[] = [
  { jobTitle: "React Dashboard for SaaS", jobDescription: "Build admin dashboard with charts and user management.", generatedContent: "I've built 10+ SaaS dashboards with React and Recharts. Can start Monday.", tone: "PROFESSIONAL", formula: "AIDA", proposalLength: "SHORT", upworkOpener: true, status: "WON" },
  { jobTitle: "Fix Node.js API Performance", jobDescription: "Our REST API is slow. Need optimization.", generatedContent: "Diagnosed and fixed similar bottlenecks before — usually N+1 queries. Happy to audit.", tone: "PROFESSIONAL", formula: "PAS", proposalLength: "SHORT", upworkOpener: false, status: "REPLIED" },
  { jobTitle: "Next.js Landing Page", jobDescription: "Marketing site for our B2B product.", generatedContent: "Here's a loom of a similar landing I shipped last month. Tight timelines welcome.", tone: "CONVERSATIONAL", formula: "BAB", proposalLength: "SHORT", upworkOpener: true, status: null },
  { jobTitle: "Stripe Integration", jobDescription: "Add subscriptions to existing Express app.", generatedContent: "Integrated Stripe Billing on 6 projects. Can reuse a battle-tested setup.", tone: "PROFESSIONAL", formula: "DIRECT", proposalLength: "SHORT", upworkOpener: false, status: "WON" },
  { jobTitle: "PostgreSQL Schema Design", jobDescription: "Design DB for a multi-tenant SaaS.", generatedContent: "Multi-tenant schema with RLS is my specialty. Can share an ERD from a past project.", tone: "PROFESSIONAL", formula: "STAR", proposalLength: "MEDIUM", upworkOpener: false, status: null },
  { jobTitle: "React Native Mobile App", jobDescription: "Cross-platform app for iOS and Android.", generatedContent: "Shipped 4 RN apps to production. Expo or bare — comfortable with both.", tone: "FRIENDLY", formula: "AIDA", proposalLength: "MEDIUM", upworkOpener: true, status: "NO_RESPONSE" },
  { jobTitle: "TypeScript Refactor", jobDescription: "Migrate JavaScript codebase to TypeScript.", generatedContent: "Migrated 80k-line codebase to TS strict mode. Know exactly where the pain points are.", tone: "PROFESSIONAL", formula: "PAS", proposalLength: "SHORT", upworkOpener: false, status: null },
  { jobTitle: "GraphQL API Build", jobDescription: "Design and build GraphQL API from scratch.", generatedContent: "Apollo + Prisma is my default stack. Can deliver a schema draft within 24 hours.", tone: "PROFESSIONAL", formula: "BAB", proposalLength: "MEDIUM", upworkOpener: false, status: "REPLIED" },
  { jobTitle: "Shopify Theme Customization", jobDescription: "Modify existing Liquid theme, fix layout issues.", generatedContent: "4 years of Liquid experience. Can fix these in a day — no guesswork.", tone: "CONVERSATIONAL", formula: "DIRECT", proposalLength: "SHORT", upworkOpener: true, status: null },
  { jobTitle: "AWS Lambda Functions", jobDescription: "Build serverless functions for data processing.", generatedContent: "Lambda + SQS pipelines are my daily work. Can scope this in a quick call.", tone: "PROFESSIONAL", formula: "AIDA", proposalLength: "SHORT", upworkOpener: false, status: "WON" },
  { jobTitle: "Bug Fixes in React App", jobDescription: "Several UI bugs in production app.", generatedContent: "Send me the repo or a loom. I'll have a fix estimate within 2 hours.", tone: "CONVERSATIONAL", formula: "DIRECT", proposalLength: "SHORT", upworkOpener: false, status: "REPLIED" },
  { jobTitle: "CI/CD Pipeline Setup", jobDescription: "Set up GitHub Actions for Node.js project.", generatedContent: "Built pipelines for 15+ teams. Can have this running in a day.", tone: "PROFESSIONAL", formula: "STAR", proposalLength: "SHORT", upworkOpener: false, status: null },
  { jobTitle: "E-commerce Site (WordPress)", jobDescription: "Build WooCommerce store with custom theme.", generatedContent: "WooCommerce store with a premium theme and payment gateway — typical turnaround is 1 week.", tone: "FRIENDLY", formula: "BAB", proposalLength: "MEDIUM", upworkOpener: true, status: "NO_RESPONSE" },
  { jobTitle: "Data Visualization Dashboard", jobDescription: "D3.js charts for analytics platform.", generatedContent: "D3 and Observable are where I live. Can prototype 3 chart types this week.", tone: "PROFESSIONAL", formula: "AIDA", proposalLength: "MEDIUM", upworkOpener: false, status: null },
  { jobTitle: "Authentication System", jobDescription: "Implement OAuth2 + JWT in Express.", generatedContent: "Auth is often copy-pasted wrong. I write it from scratch and test it properly.", tone: "PROFESSIONAL", formula: "PAS", proposalLength: "SHORT", upworkOpener: false, status: "WON" },
  { jobTitle: "Tailwind UI Components", jobDescription: "Build reusable component library.", generatedContent: "Shipped a 40-component Tailwind library last quarter. Can share the repo.", tone: "CONVERSATIONAL", formula: "BAB", proposalLength: "SHORT", upworkOpener: true, status: null },
  { jobTitle: "SEO Audit and Fixes", jobDescription: "Technical SEO improvements for Next.js app.", generatedContent: "Ran audits with Lighthouse and Screaming Frog. Know exactly what to fix.", tone: "PROFESSIONAL", formula: "STAR", proposalLength: "MEDIUM", upworkOpener: false, status: "REPLIED" },
  { jobTitle: "Freelance Platform Clone", jobDescription: "MVP of job marketplace with user profiles.", generatedContent: "Built 2 marketplace MVPs. Can share architecture doc upfront.", tone: "PROFESSIONAL", formula: "AIDA", proposalLength: "LONG", upworkOpener: false, status: null },
  { jobTitle: "Redis Caching Layer", jobDescription: "Add Redis to reduce DB load.", generatedContent: "Redis caching cut DB queries 70% on my last project. Will do the same here.", tone: "PROFESSIONAL", formula: "PAS", proposalLength: "SHORT", upworkOpener: false, status: "NO_RESPONSE" },
  { jobTitle: "Figma to React", jobDescription: "Convert Figma designs to pixel-perfect React.", generatedContent: "I work directly in Figma before writing a line of code. Zero back-and-forth.", tone: "CONVERSATIONAL", formula: "DIRECT", proposalLength: "SHORT", upworkOpener: true, status: "WON" },
  { jobTitle: "Python Web Scraper", jobDescription: "Scrape product data from e-commerce sites.", generatedContent: "Playwright + BeautifulSoup is my scraping stack. Anti-bot? Handled.", tone: "PROFESSIONAL", formula: "AIDA", proposalLength: "SHORT", upworkOpener: false, status: null },
  { jobTitle: "Socket.io Chat App", jobDescription: "Real-time chat with rooms and DMs.", generatedContent: "Built a 10k-user chat system with Socket.io. Rooms, DMs, presence — all covered.", tone: "FRIENDLY", formula: "BAB", proposalLength: "MEDIUM", upworkOpener: true, status: "REPLIED" },
  { jobTitle: "Prisma ORM Migration", jobDescription: "Migrate raw SQL queries to Prisma.", generatedContent: "Migrated 3 large codebases to Prisma. Zero data loss, full type safety.", tone: "PROFESSIONAL", formula: "STAR", proposalLength: "MEDIUM", upworkOpener: false, status: null },
  { jobTitle: "Docker Compose Setup", jobDescription: "Containerize full-stack app for dev and prod.", generatedContent: "One compose file for dev, one for prod — clean separation. Can do this today.", tone: "PROFESSIONAL", formula: "DIRECT", proposalLength: "SHORT", upworkOpener: false, status: "WON" },
  { jobTitle: "React Native Push Notifications", jobDescription: "Integrate Firebase push notifications.", generatedContent: "Firebase + Expo Notifications is a 2-day job. Done it 4 times.", tone: "CONVERSATIONAL", formula: "AIDA", proposalLength: "SHORT", upworkOpener: false, status: "NO_RESPONSE" },
  { jobTitle: "OpenAI Integration", jobDescription: "Add AI chat to existing web app.", generatedContent: "GPT-4 streaming in a React app — I shipped exactly this 3 weeks ago.", tone: "PROFESSIONAL", formula: "BAB", proposalLength: "SHORT", upworkOpener: true, status: null },
  { jobTitle: "Webflow to Next.js", jobDescription: "Rebuild Webflow site in Next.js for performance.", generatedContent: "Migrated 5 Webflow sites to Next.js. Always see a 30+ point Lighthouse improvement.", tone: "PROFESSIONAL", formula: "STAR", proposalLength: "MEDIUM", upworkOpener: false, status: "REPLIED" },
  { jobTitle: "Admin Panel (React + Django)", jobDescription: "Internal tool for managing orders.", generatedContent: "Django REST + React admin is a stack I know deeply. Can share a demo.", tone: "PROFESSIONAL", formula: "AIDA", proposalLength: "MEDIUM", upworkOpener: false, status: null },
  { jobTitle: "Unit Test Coverage", jobDescription: "Write Jest tests for React components.", generatedContent: "Testing Library + Jest — can bring coverage from 0 to 80% efficiently.", tone: "PROFESSIONAL", formula: "PAS", proposalLength: "SHORT", upworkOpener: false, status: "WON" },
  { jobTitle: "Supabase Setup", jobDescription: "Migrate from Firebase to Supabase.", generatedContent: "Supabase migration guide I wrote got 200 bookmarks. Can walk you through it.", tone: "CONVERSATIONAL", formula: "DIRECT", proposalLength: "SHORT", upworkOpener: true, status: null },
  { jobTitle: "Email Automation (SendGrid)", jobDescription: "Transactional emails for user lifecycle.", generatedContent: "Welcome, onboarding, churn — all three sequences ready to adapt.", tone: "PROFESSIONAL", formula: "AIDA", proposalLength: "SHORT", upworkOpener: false, status: "NO_RESPONSE" },
  { jobTitle: "Performance Audit (React)", jobDescription: "App feels sluggish, need profiling.", generatedContent: "React DevTools + bundle analyzer — I'll find the culprit within an hour.", tone: "PROFESSIONAL", formula: "PAS", proposalLength: "SHORT", upworkOpener: false, status: "REPLIED" },
  { jobTitle: "Tailwind Migration (Bootstrap)", jobDescription: "Replace Bootstrap with Tailwind.", generatedContent: "Done this for 6 projects. Class-by-class, no regressions.", tone: "PROFESSIONAL", formula: "BAB", proposalLength: "MEDIUM", upworkOpener: false, status: null },
  { jobTitle: "Cloudinary Image Pipeline", jobDescription: "Optimize image uploads and delivery.", generatedContent: "Cloudinary transformations + signed uploads — standard setup, done in a day.", tone: "CONVERSATIONAL", formula: "DIRECT", proposalLength: "SHORT", upworkOpener: true, status: "WON" },
  { jobTitle: "WordPress Plugin Development", jobDescription: "Custom plugin for membership site.", generatedContent: "10+ WP plugins shipped. Hooks, shortcodes, REST API — all covered.", tone: "PROFESSIONAL", formula: "AIDA", proposalLength: "MEDIUM", upworkOpener: false, status: null },
  { jobTitle: "API Rate Limiting", jobDescription: "Add rate limiting to Express endpoints.", generatedContent: "express-rate-limit + Redis sliding window — 30-minute job.", tone: "PROFESSIONAL", formula: "DIRECT", proposalLength: "SHORT", upworkOpener: false, status: "NO_RESPONSE" },
  { jobTitle: "Zod Schema Validation", jobDescription: "Add runtime validation to API layer.", generatedContent: "Zod end-to-end — request, response, and shared types. Can set up the pattern.", tone: "PROFESSIONAL", formula: "STAR", proposalLength: "SHORT", upworkOpener: false, status: null },
  { jobTitle: "Mapbox Integration", jobDescription: "Add interactive map to real estate app.", generatedContent: "Mapbox GL + React — clustering, popups, custom layers. Happy to show a demo.", tone: "CONVERSATIONAL", formula: "AIDA", proposalLength: "MEDIUM", upworkOpener: true, status: "REPLIED" },
  { jobTitle: "PDF Generation (Node.js)", jobDescription: "Generate invoices as PDFs.", generatedContent: "Puppeteer or Pdfkit — depends on complexity. Can recommend after seeing the design.", tone: "PROFESSIONAL", formula: "PAS", proposalLength: "SHORT", upworkOpener: false, status: null },
  { jobTitle: "Zustand State Management", jobDescription: "Replace Redux with lighter state manager.", generatedContent: "Zustand migration from Redux is usually a net 40% code reduction. Have a template.", tone: "PROFESSIONAL", formula: "BAB", proposalLength: "SHORT", upworkOpener: false, status: "WON" },
  { jobTitle: "Mobile-Responsive Fixes", jobDescription: "Several pages break on mobile.", generatedContent: "Send me the URLs. Usually fixable in half a day with proper media queries.", tone: "CONVERSATIONAL", formula: "DIRECT", proposalLength: "SHORT", upworkOpener: false, status: "NO_RESPONSE" },
  { jobTitle: "Webhook Handler (Stripe)", jobDescription: "Handle Stripe webhook events reliably.", generatedContent: "Idempotency keys + signature verification — the two things most people miss. I don't.", tone: "PROFESSIONAL", formula: "PAS", proposalLength: "SHORT", upworkOpener: false, status: null },
  { jobTitle: "Microservices Architecture", jobDescription: "Break monolith into services.", generatedContent: "Event-driven with RabbitMQ or SQS — depends on scale. Let's talk scope.", tone: "PROFESSIONAL", formula: "STAR", proposalLength: "LONG", upworkOpener: false, status: "REPLIED" },
  { jobTitle: "Landing Page A/B Test", jobDescription: "Set up A/B testing with analytics.", generatedContent: "Posthog feature flags + conversion tracking — quick to wire up.", tone: "CONVERSATIONAL", formula: "AIDA", proposalLength: "SHORT", upworkOpener: true, status: null },
  { jobTitle: "React Query Refactor", jobDescription: "Replace custom fetch logic with React Query.", jobUrl: "https://upwork.com/jobs/react-query", generatedContent: "TanStack Query v5 migration — I know the API inside out. Can do it incrementally.", tone: "PROFESSIONAL", formula: "BAB", proposalLength: "MEDIUM", upworkOpener: false, status: "WON" },
  { jobTitle: "Node.js Cron Jobs", jobDescription: "Scheduled tasks for data sync and cleanup.", generatedContent: "node-cron + queue with retries — reliable pattern I use on every project.", tone: "PROFESSIONAL", formula: "DIRECT", proposalLength: "SHORT", upworkOpener: false, status: null },
  { jobTitle: "Error Monitoring (Sentry)", jobDescription: "Integrate Sentry into production app.", generatedContent: "Source maps + custom contexts — Sentry actually useful, not just noise.", tone: "PROFESSIONAL", formula: "AIDA", proposalLength: "SHORT", upworkOpener: false, status: "NO_RESPONSE" },
  { jobTitle: "Full-Stack MVP (4 weeks)", jobDescription: "Build product from scratch, fast.", generatedContent: "Next.js + Supabase + Stripe — my default MVP stack. Can share a scoping doc.", tone: "PROFESSIONAL", formula: "STAR", proposalLength: "LONG", upworkOpener: true, status: "REPLIED" },
  { jobTitle: "Accessibility Audit (WCAG)", jobDescription: "Improve WCAG 2.1 compliance.", generatedContent: "Axe + screen reader testing. Will give you a prioritized fix list.", tone: "PROFESSIONAL", formula: "PAS", proposalLength: "MEDIUM", upworkOpener: false, status: null },
  { jobTitle: "Search with Algolia", jobDescription: "Add full-text search to product catalog.", generatedContent: "Algolia InstantSearch + React — can have a prototype running today.", tone: "CONVERSATIONAL", formula: "AIDA", proposalLength: "SHORT", upworkOpener: true, status: "WON" },
  { jobTitle: "Monorepo Setup (Turborepo)", jobDescription: "Organize shared code across apps.", generatedContent: "Turborepo + pnpm workspaces — set this up 3 times this year. Very clean.", tone: "PROFESSIONAL", formula: "DIRECT", proposalLength: "SHORT", upworkOpener: false, status: null },
  { jobTitle: "Figma Design System", jobDescription: "Build component library in Figma.", generatedContent: "Auto-layout + variables + dev mode handoff — full system, not just frames.", tone: "PROFESSIONAL", formula: "BAB", proposalLength: "MEDIUM", upworkOpener: false, status: "NO_RESPONSE" },
  { jobTitle: "Chart.js to Recharts Migration", jobDescription: "Replace Chart.js with Recharts.", generatedContent: "Recharts is more composable — migration is mostly 1:1 with some cleanup wins.", tone: "CONVERSATIONAL", formula: "PAS", proposalLength: "SHORT", upworkOpener: false, status: "REPLIED" },
  { jobTitle: "Drizzle ORM Setup", jobDescription: "Migrate from Prisma to Drizzle ORM.", generatedContent: "Drizzle + Postgres — I've done both sides of this migration. Will be smooth.", tone: "PROFESSIONAL", formula: "STAR", proposalLength: "MEDIUM", upworkOpener: false, status: null },
  { jobTitle: "Playwright E2E Tests", jobDescription: "Write end-to-end tests for checkout flow.", generatedContent: "Playwright page objects + CI integration — checkout tests are my go-to demo.", tone: "PROFESSIONAL", formula: "AIDA", proposalLength: "SHORT", upworkOpener: false, status: "WON" },
  { jobTitle: "Payment Gateway (PayPal)", jobDescription: "Add PayPal as alternative to Stripe.", generatedContent: "PayPal SDK is rough but I've tamed it on 3 projects. No surprises.", tone: "PROFESSIONAL", formula: "PAS", proposalLength: "SHORT", upworkOpener: false, status: null },
  { jobTitle: "React Context Refactor", jobDescription: "Replace prop drilling with Context API.", generatedContent: "Context + useReducer refactor — can usually halve the prop chains.", tone: "PROFESSIONAL", formula: "BAB", proposalLength: "SHORT", upworkOpener: false, status: "NO_RESPONSE" },
  { jobTitle: "SSR Performance (Next.js)", jobDescription: "Reduce TTFB on server-rendered pages.", generatedContent: "ISR + streaming with Suspense — TTFB under 200ms is achievable here.", tone: "PROFESSIONAL", formula: "STAR", proposalLength: "MEDIUM", upworkOpener: false, status: null },
  { jobTitle: "Google Maps Integration", jobDescription: "Embed maps with markers and directions.", generatedContent: "Maps JS API + Places autocomplete — standard setup, done in a day.", tone: "CONVERSATIONAL", formula: "DIRECT", proposalLength: "SHORT", upworkOpener: true, status: "REPLIED" },
  { jobTitle: "Multi-language Support (i18n)", jobDescription: "Add English and Spanish to Next.js app.", generatedContent: "next-intl with locale routing — clean setup, no runtime overhead.", tone: "PROFESSIONAL", formula: "AIDA", proposalLength: "MEDIUM", upworkOpener: false, status: "WON" },
];
